### ISSUE TITLE
Impossible to find mdl in a gemset

### ISSUE THREAD

**Issue by astorije** [leonelgalan/linter-markdownlint#3]
When `mdl` is installed in a gemset, `linter-markdownlint` cannot find it and this error pops up:

```
Failed to run undefined
spawn mdl ENOENT
```

Setting the executable dir to something like the following outputs the exact same error:

``` sh
GEM_PATH=~/.rvm/gems/ruby-2.3.1@cht_docs/ ~/.rvm/gems/ruby-2.3.1@cht_docs/bin/mdl
```

(Same when expanding `~` to the actual user dir)

**Comment by timotree3** [comment]
I don't know what you mean by a gemset but I get this same error with mdl in any folder.

**Comment by leonelgalan** [comment]
What happens when you type `which mdl` in your terminal? I'm sure setting the GEM_PATH and expanding `~` ultimately results in a path, that once plugged in into the settings should work.

**Comment by astorije** [comment]
Hey @leonelgalan! Sorry, I opened that ticket more than a year ago and since then my team has grown by a ton and tools were switched, so I'm not sure what was the deal with this anymore.

Also, I meant a Gemfile :man_facepalming:
